[IMP] hr_shift: Prevent TypeError
Use case example:
- Create an hr.shift.planning.line record with a start time of 00:00:00 and an end time of 08:00:00
- The employee must have a work schedule after 08:00:00 (for example, starting at 13:00:00)
- The report from the hr_attendance_report_theoretical_time module is used. The hr_shift methods will mix records and cause an error.

TypeError: cannot union different models: 'hr.shift.planning.line()' and 'resource.calendar.attendance()'

TT60298